In [1]:
from pathlib import Path
import pandas as pd

In [5]:
# read CSV and create Pandas dataframe
df = pd.read_csv("trip_data.csv",
                index_col="request_datetime",
                infer_datetime_format=True,
                parse_dates=True)

# preview df
display(df)

# df info
display(df.info())

C:\Users\raynolds\AppData\Local\Temp\ipykernel_8984\2474507294.py:2: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df = pd.read_csv("trip_data.csv",

,hvfhs_license_num,dispatching_base_num,originating_base_num,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,trip_time,...,sales_tax,congestion_surcharge,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag
request_datetime,,,,,,,,,,,,,,,,,,,,,
2023-01-01 01:23:54,HV0003,B03404,B03404,2023-01-01 01:32:20,2023-01-01 01:34:04,2023-01-01 01:45:04,235,18,2.060,660,...,2.12,0.00,0.0,0.0,14.02,N,N,,N,N
2023-01-01 01:58:19,HV0003,B03404,B03404,2023-01-01 02:02:31,2023-01-01 02:02:53,2023-01-01 02:25:52,37,33,4.380,1379,...,3.70,0.00,0.0,0.0,33.24,N,N,,N,N
2023-01-01 01:59:09,HV0003,B03404,B03404,2023-01-01 02:02:30,2023-01-01 02:04:02,2023-01-01 02:13:52,232,148,1.390,590,...,3.02,2.75,0.0,0.0,45.18,N,N,,N,N
2023-01-01 02:14:02,HV0003,B03404,B03404,2023-01-01 02:22:59,2023-01-01 02:23:19,2023-01-01 02:31:00,255,256,1.240,461,...,3.17,0.00,0.0,0.0,31.67,N,N,,N,N
2023-01-01 02:16:53,HV0003,B03404,B03404,2023-01-01 02:23:39,2023-01-01 02:24:02,2023-01-01 02:41:11,223,129,2.760,1029,...,2.46,0.00,0.0,0.0,22.54,N,N,,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31 22:08:52,HV0005,B03406,NaN,NaN,2023-12-31 22:20:42,2023-12-31 22:43:17,60,244,4.694,1355,...,5.25,0.00,0.0,0.0,20.30,N,N,N,N,N
2023-12-31 22:17:11,HV0005,B03406,NaN,NaN,2023-12-31 22:23:08,2023-12-31 22:44:52,188,165,4.222,1304,...,3.82,0.00,0.0,0.0,17.96,N,N,N,N,N
2023-12-31 22:30:20,HV0003,B03404,B03404,2023-12-31 22:34:13,2023-12-31 22:36:14,2023-12-31 22:59:56,225,148,5.470,1422,...,2.25,2.75,0.0,0.0,20.55,N,N,N,N,N
2023-12-31 22:31:17,HV0003,B03404,B03404,2023-12-31 22:33:22,2023-12-31 22:35:24,2023-12-31 23:23:07,65,50,6.140,2863,...,3.05,2.75,0.0,0.0,39.12,N,N,N,N,Y
2023-12-31 23:14:42,HV0005,B03406,NaN,NaN,2023-12-31 23:21:14,2023-12-31 23:30:29,72,85,1.236,555,...,0.94,0.00,0.0,0.0,6.91,N,N,N,N,N

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 12000 entries, 2023-01-01 01:23:54 to 2023-12-31 23:14:42
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   hvfhs_license_num     12000 non-null  object
 1   dispatching_base_num  12000 non-null  object
 2   originating_base_num  8603 non-null   object
 3   on_scene_datetime     8603 non-null   object
 4   pickup_datetime       12000 non-null  object
 5   dropoff_datetime      12000 non-null  object
 6   PULocationID          12000 non-null  int64
 7   DOLocationID          12000 non-null  int64
 8   trip_miles            12000 non-null  float64
 9   trip_time             12000 non-null  int64
 10  base_passenger_fare   12000 non-null  float64
 11  tolls                 12000 non-null  float64
 12  bcf                   12000 non-null  float64
 13  sales_tax             12000 non-null  float64
 14  congestion_surcharge  12000 non-null  float64
 15  airport_fee           12000 non-null  float64
 16  tips                  12000 non-null  float64
 17  driver_pay            12000 non-null  float64
 18  shared_request_flag   12000 non-null  object
 19  shared_match_flag     12000 non-null  object
 20  access_a_ride_flag    12000 non-null  object
 21  wav_request_flag      12000 non-null  object
 22  wav_match_flag        12000 non-null  object
dtypes: float64(9), int64(3), object(11)
memory usage: 2.2+ MB

None

In [3]:
# IMPROVE READABILITY OF DF (anticipating OneHotEncoder readability)

# access taxi zone csv
location_encoding_csv = pd.read_csv(Path("./encoding_keys_nyc/taxi_zone_lookup.csv"))

#1. create columns for boroughs and populate with borough names
# create a dictionary of boroughs based on LocationID
borough_id_dict = dict(zip(location_encoding_csv["LocationID"], location_encoding_csv["Borough"]))
# replace location id with borough columns
df["PUborough"] = df["PULocationID"].replace(borough_id_dict)
df["DOborough"] = df["PULocationID"].replace(borough_id_dict)

# 2 - convert ID to zone text
# create a dictionary of locations based on LocationID
zone_id_dict = dict(zip(location_encoding_csv["LocationID"], location_encoding_csv["Zone"]))
# replace location ID with zone name
df["PULocationID"].replace(zone_id_dict, inplace=True)
df["DOLocationID"].replace(zone_id_dict, inplace=True)

# 3 - convert "hvfhs_license_num" to company name (using data_dictionary_trip_records_hvfhs.pdf)
# create dictionary for companies, using PDF
companies_dict = {
    "HV0002": "Juno",
    "HV0003": "Uber",
    "HV0004": "Via",
    "HV0005": "Lyft"
}
# replace company code with company name
df["hvfhs_license_num"].replace(companies_dict, inplace=True)

# preview new columns in df
df.head()

,request_datetime,hvfhs_license_num,dispatching_base_num,originating_base_num,on_scene_datetime,pickup_datetime,dropoff_datetime,PULocationID,DOLocationID,trip_miles,...,airport_fee,tips,driver_pay,shared_request_flag,shared_match_flag,access_a_ride_flag,wav_request_flag,wav_match_flag,PUborough,DOborough
0,2023-01-01 01:23:54,Uber,B03404,B03404,2023-01-01 01:32:20,2023-01-01 01:34:04,2023-01-01 01:45:04,University Heights/Morris Heights,Bedford Park,2.06,...,0.0,0.0,14.02,N,N,,N,N,Bronx,Bronx
1,2023-01-01 01:58:19,Uber,B03404,B03404,2023-01-01 02:02:31,2023-01-01 02:02:53,2023-01-01 02:25:52,Bushwick South,Brooklyn Heights,4.38,...,0.0,0.0,33.24,N,N,,N,N,Brooklyn,Brooklyn
2,2023-01-01 01:59:09,Uber,B03404,B03404,2023-01-01 02:02:30,2023-01-01 02:04:02,2023-01-01 02:13:52,Two Bridges/Seward Park,Lower East Side,1.39,...,0.0,0.0,45.18,N,N,,N,N,Manhattan,Manhattan
3,2023-01-01 02:14:02,Uber,B03404,B03404,2023-01-01 02:22:59,2023-01-01 02:23:19,2023-01-01 02:31:00,Williamsburg (North Side),Williamsburg (South Side),1.24,...,0.0,0.0,31.67,N,N,,N,N,Brooklyn,Brooklyn
4,2023-01-01 02:16:53,Uber,B03404,B03404,2023-01-01 02:23:39,2023-01-01 02:24:02,2023-01-01 02:41:11,Steinway,Jackson Heights,2.76,...,0.0,0.0,22.54,N,N,,N,N,Queens,Queens